language: cpp
sudo: required
dist: xenial

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

compiler:
  - gcc

install:
  - ./infotainment-install.sh
  - sudo apt install graphviz

script: 
  - doxygen Doxyfile

  - cd Software/
  - sed -i 's/#define RPI 1/\/\/#define RPI 1/g' ./MainApp/inc/config.h
  - ./BuildAll.sh
  - ./Tests/OBD2_test/Offline/bin/OBD2OfflineTest
  - ./Tests/Sensors_test/Board_test/Offline/bin/SensorBoardOfflineTest
  - ./Tests/Sensors_test/MMA8652_test/Offline/bin/MMA8652OfflineTest
  - ./Tests/Sensors_test/Mux_test/Offline/bin/MuxOfflineTest
  - ./Tests/Sensors_test/Ultrasonic_test/Offline/bin/UltrasonicOfflineTest 

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: Docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master