language: cpp
sudo: required
dist: xenial

compiler:
  - gcc
  - clang

install:
  - ./infotainment-install.sh

script: 
  - cd Software/
  - ./BuildAll.sh
  - ./Tests/OBD2_test/Offline/bin/OBD2OfflineTest
  - ./Tests/Sensors_test/Board_test/Offline/bin/SensorBoardOfflineTest
  - ./Tests/Sensors_test/MMA8652_test/Offline/bin/MMA8652OfflineTest
  - ./Tests/Sensors_test/Mux_test/Offline/bin/MuxOfflineTest
  - ./Tests/Sensors_test/Ultrasonic_test/Offline/bin/UltrasonicOfflineTest 